### ISSUE TITLE
The ability to search manually

### ISSUE THREAD

**Issue by Shatur95** [Guyutongxue/VSC_CppReference#1]
Hi! Thank you for the extension.
I would like to suggest to add the ability to search in `cppreference` manually. This will be convenient for cases when you need to read the documentation about a type that is not located in the current source file.

**Comment by Guyutongxue** [comment]
Thanks for your suggestion. I will consider adding this feature in the future.

**Comment by Guyutongxue** [comment]
New version released. Now you can search manually by typing command `cppref.search` on Command Palette.

**Comment by Shatur95** [comment]
Thank you!
