### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by Guyutongxue** [Guyutongxue/VSC_CppReference#2]

**Comment by MiChuancey** [comment]
同感，希望支持修改黑色背景，因为vscode默认就是黑色的。现在cpp reference是白色的，显得很突兀，希望能支持这个功能。
![image](https://user-images.githubusercontent.com/37216768/188620907-9522de01-4cdb-4c9e-a601-81f31e61d5b1.png)

**Comment by justcyl** [comment]
似乎加个css滤镜就行了
body{
    filter: invert(100%) hue-rotate(180deg) brightness(115%) contrast(95%) !important;
}
