### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by hrishikesh-deshpande** [Guyutongxue/VSC_CppReference#3]
When trying to search, I am getting the following notification. How to solve this?

request to https://en.cppreference.com/mwiki/api.php?action=query&list=search&srsearch=hash&format=xml&srlimit=50&srprop=titlesnippet failed, reason: certificate has expired

-Hrishikesh

**Comment by Guyutongxue** [comment]
Seems that cppreference.com now refused to show the search result in XML format. A fix will publish later.

**Comment by Guyutongxue** [comment]
Related to node-fetch/node-fetch#568. A fix will be published later.
