### ISSUE TITLE
Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by TaivasJumala** [guyutongxue/VSC_CppReference#6]
Cannot read properties of undefined (reading 'filter')

**Comment by Guyutongxue** [comment]
Known issue. When the extension is not fully activated, some data will be `undefined` and an error will be thrown. This is a one-time (per each window) error and can be resolved by trying again.

PRs are welcomed.

**Comment by guyutongxue** [comment]
Seems fixed at v0.2.4.
